general {
    lock_cmd = $HOME/.config/hypr/lockbg.sh && hyprlock
    before_sleep = loginctl lock-session
    after_sleep = niri msg action power-on-monitors
}

listener {
    timeout = 300
    on-timeout = pidof hyprlock || hyprlock
}

listener {
    timeout = 600
    on-timeout = niri msg action power-off-monitors
}
