#!/usr/bin/env bash

wall_dir="$HOME/.config/swaybg/walls"
cache_dir="$HOME/.cache/thumbnails/bgselector"

mkdir -p "$wall_dir"
mkdir -p "$cache_dir"

# Generate thumbnails
find "$wall_dir" -type f \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.webp' \) | while read -r imagen; do
	filename="$(basename "$imagen")"
	thumb="$cache_dir/$filename"
	echo $thumb
	if [ ! -f "$thumb" ]; then
		magick "$imagen" -strip -thumbnail x540^ -gravity center -extent 262x540 "$thumb"
	fi
done

# List wallpapers with icons for rofi
wall_selection=$(ls "$wall_dir" | while read -r A; do echo -en "$A\x00icon\x1f$cache_dir/$A\n"; done | rofi -dmenu -config "$HOME/.config/rofi/bgselector.rasi")

# Set wallpaper and update waybar color
if [ -n "$wall_selection" ]; then
    pkill swaybg 2>/dev/null
    swaybg -i "${wall_dir}/${wall_selection}" -m fill &
else
	exit 1
fi
