#!/usr/bin/env bash

shutdown="  "
reboot="  "
lock="  "
logout="  "

options="$shutdown\n$reboot\n$lock\n$logout"
chosen="$(echo -e "$options" | rofi -dmenu -config "$HOME/.config/rofi/powermenu.rasi" -p "Power Menu")"

case "$chosen" in
  "$shutdown")
    ~/.config/rofi/scripts/rofi-confirm "Shutdown?" poweroff
    ;;
  "$reboot")
    ~/.config/rofi/scripts/rofi-confirm "Reboot?" reboot
    ;;
  "$lock")
    $HOME/.config/hypr/lockbg.sh && hyprlock
    ;;
  "$logout")
    ~/.config/rofi/scripts/rofi-confirm "Logout?" niri msg action quit
    ;;
  *)
    exit 0
    ;;
esac
